import {
  TbBrandGithub,
  TbBrandFacebook,
  TbBrandInstagram,
  TbBrandLinkedin,
  TbMail,
  TbBrandTwitter,
  TbBrandTwitch,
  TbBrandYoutube,
  TbBrandWhatsapp,
  TbBrandSnapchat,
  TbBrandPinterest,
  TbBrandTiktok,
  TbBrandCodepen,
  TbBrandDiscord,
  TbBrandGitlab,
  TbBrandReddit,
  TbBrandSkype,
  TbBrandSteam,
  TbBrandTelegram,
  TbBrandMastodon,
  TbFileDescription,
  TbBrandDatabricks,
} from "react-icons/tb";

const socialIcons = {
  Github: TbBrandGithub,
  Facebook: TbBrandFacebook,
  Instagram: TbBrandInstagram,
  LinkedIn: TbBrandLinkedin,
  Mail: TbMail,
  Twitter: TbBrandTwitter,
  Twitch: TbBrandTwitch,
  YouTube: TbBrandYoutube,
  WhatsApp: TbBrandWhatsapp,
  Snapchat: TbBrandSnapchat,
  Pinterest: TbBrandPinterest,
  TikTok: TbBrandTiktok,
  CodePen: TbBrandCodepen,
  Discord: TbBrandDiscord,
  GitLab: TbBrandGitlab,
  Reddit: TbBrandReddit,
  Skype: TbBrandSkype,
  Steam: TbBrandSteam,
  Telegram: TbBrandTelegram,
  Mastodon: TbBrandMastodon,
  Resume: TbFileDescription,
  Projects: TbBrandDatabricks,
};

export default socialIcons;
